//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityAppData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Courses()
        {
            this.Courses1 = new HashSet<Courses>();
            this.CoursesTime = new HashSet<CoursesTime>();
        }
    
        public int Course_ID { get; set; }
        public string Course_Name { get; set; }
        public Nullable<int> Practical_Hours { get; set; }
        public Nullable<int> Theory_Hours { get; set; }
        public int Total_Hours { get; set; }
        public int FK_Major_ID { get; set; }
        public Nullable<int> Practical_Units { get; set; }
        public Nullable<int> Theory_Units { get; set; }
        public int Total_Units { get; set; }
        public Nullable<int> FK_Prerequisite { get; set; }
    
        public virtual Majors Majors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Courses> Courses1 { get; set; }
        public virtual Courses Courses2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursesTime> CoursesTime { get; set; }
    }
}
