//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityAppData.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversityDB_AdvancedEntities : DbContext
    {
        public UniversityDB_AdvancedEntities()
            : base("name=UniversityDB_AdvancedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<CoursesTime> CoursesTime { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Levels> Levels { get; set; }
        public virtual DbSet<Majors> Majors { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Teacher_Degree> Teacher_Degree { get; set; }
        public virtual DbSet<Term> Term { get; set; }
    }
}
